// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THONK.Resources.Database;

namespace THONK.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20181124223924_update1")]
    partial class update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("THONK.Resources.Database.Guild", b =>
                {
                    b.Property<ulong>("GuildID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelAnnouncements");

                    b.Property<ulong>("ChannelBotLog");

                    b.Property<ulong>("ChannelGeneral");

                    b.Property<ulong>("ChannelLog");

                    b.Property<string>("Prefix");

                    b.Property<ulong>("RoleGeneral");

                    b.Property<ulong>("RoleGuest");

                    b.Property<ulong>("RoleInitiate");

                    b.Property<ulong>("RoleLieutenant");

                    b.Property<ulong>("RoleSergeant");

                    b.Property<ulong>("RoleSoldier");

                    b.Property<ulong>("RoleWarlord");

                    b.HasKey("GuildID");

                    b.ToTable("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
